fix(CDC_OPTIONS): Use boolean value for cdc preimage option
CDC_SETTINGS_NAMES_VALUES['preimage'] uses string values "true" "false"
instead of bool True False. This cause assertion error if it was changed

```
AssertionError: CDC extension settings are differs.
Current: {'delta': 'full', 'enabled': True, 'preimage': True, 'postimage': True, 'ttl': '1800'}
expected: {'delta': 'full', 'enabled': True, 'preimage': 'true', 'postimage': True, 'ttl': '1800'}
```